### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by NickStallman** [lightSAML/lightSAML#100]
I found it a bit of a battle trying to implement lightSAML in to an existing application (CodeIgniter) as the documentation is poor if you aren't using Symfony it would see.

My intention is to use a generic SAML library that can be implemented in a range of existing systems, some CodeIgniter, some third party, etc...

Here is a basic implementation I've done which seems to work and should be moderately secure (verifies signatures, checks timestamps but does not handle encryption).
Verified working against a Gluu IDP

`	function metadata()
	{
		$public = new \LightSaml\Credential\X509Certificate();
		$public->loadPem($this->settings['sp']['x509cert']);
		
		$entityDescriptor = new \LightSaml\Model\Metadata\EntityDescriptor();
		$entityDescriptor
			->setID(\LightSaml\Helper::generateID())
			->setEntityID(site_url())
		;

		$entityDescriptor->addItem(
			$spSsoDescriptor = (new \LightSaml\Model\Metadata\SpSsoDescriptor())
				->setWantAssertionsSigned(true)
		);

		$spSsoDescriptor->addKeyDescriptor(
			$keyDescriptor = (new \LightSaml\Model\Metadata\KeyDescriptor())
				->setUse(\LightSaml\Model\Metadata\KeyDescriptor::USE_SIGNING)
				->setCertificate($public)
		);

		$spSsoDescriptor->addAssertionConsumerService(
			$acs = (new \LightSaml\Model\Metadata\AssertionConsumerService())
				->setBinding(\LightSaml\SamlConstants::BINDING_SAML2_HTTP_POST)
				->setLocation(site_url('user/acs'))
		);
		
		$serializationContext = new \LightSaml\Model\Context\SerializationContext();
		$entityDescriptor->serialize($serializationContext->getDocument(), $serializationContext);
		
		header('Content-Type: application/xml');
		die($serializationContext->getDocument()->saveXML());
	}

	function acs()
	{
		$saml = $this->input->get_post('SAMLResponse');
		if (empty($saml))
		{
			$authnRequest = new \LightSaml\Model\Protocol\AuthnRequest();
			$authnRequest
				->setAssertionConsumerServiceURL(site_url('user/acs'))
				->setProtocolBinding(\LightSaml\SamlConstants::BINDING_SAML2_HTTP_POST)
				->setID(\LightSaml\Helper::generateID())
				->setIssueInstant(new \DateTime())
				->setDestination($this->settings['idp']['url'])
				->setIssuer(new \LightSaml\Model\Assertion\Issuer(site_url()));
			
			$bindingFactory = new \LightSaml\Binding\BindingFactory();
			$redirectBinding = $bindingFactory->create(\LightSaml\SamlConstants::BINDING_SAML2_HTTP_REDIRECT);
			
			$messageContext = new \LightSaml\Context\Profile\MessageContext();
			$messageContext->setMessage($authnRequest);

			$httpResponse = $redirectBinding->send($messageContext);
			header('Location: '.$httpResponse->getTargetUrl());
			die();
		}
		
		$request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();

		$bindingFactory = new \LightSaml\Binding\BindingFactory();
		$binding = $bindingFactory->getBindingByRequest($request);

		$messageContext = new \LightSaml\Context\Profile\MessageContext();
		$binding->receive($request, $messageContext);
		
		$response = $messageContext->asResponse();

		$idpPublic = new \LightSaml\Credential\X509Certificate();
		$idpPublic->loadPem($this->settings['idp']['cert']);
		$signature = $response->getSignature();

		try {
			$ok = $signature->validate($key);
			if (!$ok) {
				die('Sorry, the signature was not correct');
			}
		} catch (\Exception $ex) {
			die('Sorry, the signature failed');
		}
		
		$assertion = $response->getFirstAssertion();
		if (empty($assertion))
			die("Sorry, no assertion");
		
		foreach ($assertion->getConditions() as $condition)
		{
			$notBefore = $condition->getNotBeforeTimestamp();
			if (!empty($notBefore) && time() < $notBefore)
				die('Invalid notBefore');
		
			$notOnOrAfter = $condition->getNotOnOrAfterTimestamp();
			if (!empty($notOnOrAfter) && time() > $notOnOrAfter)
				die('Invalid notOnOrAfter, expired');
		}
		
		$full_attributes = array();
		$short_attributes = array();
		
		foreach ($assertion->getAllAttributeStatements() as $attribute)
		{
			$full_attributes[$attribute->getName()] = $attribute->getFirstAttributeValue();
			$short_attributes[$attribute->getFriendlyName()] = $attribute->getFirstAttributeValue();
		}
		
		var_dump($short_attributes);die();
	}`

The settings array is quite simple and looks like this:

`$this->settings = array(
		'cert' => '',
		'privateKey' => '',
        ),
		'idp' => array(
			'entityId' => '',
			'url' => '',
			'logout' => '',
			'cert' => '',
		)
    );`

It would be great if there was an official basic implementation in the cookbook of a standard SP login process.

**Comment by tmilos** [comment]
You should take use of implemented profiles and all embeded features. Take a look at https://github.com/lightSAML/lightSAML/tree/master/web/sp - it's not using symofny
