### ISSUE TITLE
RequestStateStoreInterface - clear() method.

### ISSUE THREAD

**Issue by pbytniewski-neurosys** [lightSAML/lightSAML#102]
Hello, 
I've almost sucessfully written custom RequestStateStore, however I don't really undestand what clear method is supposed to do. Additionaly I haven't found any usage of it using  php storm. Is the method obsolete? If not, what should it do ?

**Comment by tmilos** [comment]
It's not used directly by LightSAML, you can implemented it for your own convenience if you want to be able to empty the store for some reason. Otherwise, for only LightSAML usage you can just throw an exception in it
