### ISSUE TITLE
Potential SAML vuln

### ISSUE THREAD

**Issue by westende** [lightSAML/lightSAML#108]
Yesterday a vuln in various SAML libs was published: https://www.kb.cert.org/vuls/id/475445
Is there any information regarding whether lightSAML is affected?

**Comment by tmilos** [comment]
Thank you for raising this issue. As I can understand the vulnerability, I don't find LightSAML and PHP itself affected according to https://3v4l.org/AXQDc and https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Model/AbstractSamlModel.php#L148

PHP XML API that reads text content from the node reads whole text, both before and after the comment, so inserting comments in the assertion node text nodes will still result with same values.

If you on the other hand could find a sample case demonstrating this vulnerability, please DM it to me

**Comment by westende** [comment]
Thank you for your quick feedback.

As I understand the blog post referenced in the report the vuln is enabled by three conditions:

1. SAML Responses contain strings that identify the authenticating user.
2. XML canonicalization (in most cases) will remove comments as part of signature validation, so adding comments to a SAML Response will not invalidate the signature.
3. XML text extraction may only return a substring of the text within an XML element when comments are present.

As you have demonstrated in https://3v4l.org/AXQDc the PHP XML API indeed is not vulnerable to this because the XML text extraction does not return a substring when comments are present. Therefor condition 3 is not met.
