### ISSUE TITLE
Invalid SAML2 timestamp

### ISSUE THREAD

**Issue by JEDIBC** [lightSAML/lightSAML#111]
Hi,

I have to deal with a saml IDP which return dateTime in the form `2018-03-07T09:53:35.000+00:00`.
It's a valid `xsd:dateTime` implementation (see http://books.xmlschemata.org/relaxng/ch19-77049.html) but it isn't accepted by `\LightSaml\Helper::parseSAMLTime` and lead to an `InvalidArgumentException`.

**Comment by tmilos** [comment]
Fixed with merged #112 and released in [v1.3.6](https://github.com/lightSAML/lightSAML/releases/tag/1.3.6)
