### ISSUE TITLE
sp metadata?

### ISSUE THREAD

**Issue by yivi** [lightSAML/lightSAML#116]
When establishing trust with an IDP, the first thing they ask us for is our SP metadata, containing our claims.

How and where do we find this information when using lightSAML?

**Comment by yivi** [comment]
Found this in the old repo:
https://github.com/aerialship/lightsaml/issues/2

Which would be exactly what I need. Was it ever merged into lightSAML/lightSAML?

**Comment by tmilos** [comment]
It was deleted from lightSaml. Maybe this can help you https://www.lightsaml.com/LightSAML-Core/Cookbook/How-to-make-entity-descriptor/

**Comment by yivi** [comment]
Too bad about it being deleted. Seemed something useful to have.

I saw that cookbook, but not being an SAML person I wasn't sure that the "entity descriptor" was equivalent to the "SP metadata" I'm being requested. And if it was, if I was going to generate it with the proper fields in it.

But I guess that with that we can roll our own command / endpoint and hope that the our AD people are satisfied with the resulting XML. And if not, try again. And again. :P

Thanks!
