### ISSUE TITLE
Documentation error in "How to receive a SAML message"

### ISSUE THREAD

**Issue by pnicolcev-tulipretail** [lightSAML/lightSAML#120]
The docs [here](https://www.lightsaml.com/LightSAML-Core/Cookbook/How-to-receive-SAML-message/) say:
```
/** @var \LightSaml\Model\Protocol\Response $response */
$response = $binding->receive($request, $messageContext);
print $response->getID();
```

However the binding::receive function doesn't return anything. 
https://github.com/lightSAML/lightSAML/blob/877b07915202d6ce344836c930557aed4168eed0/src/LightSaml/Binding/HttpPostBinding.php#L59

It does set properties on $messageContext so the fix is to getID on $messageContext.

**Comment by mclaurent** [comment]
Heya
MessageContext doesn't seem to have a getId() method. Closest I got was:
`$messageContext->getMessage()->getId()`

**Comment by biechao** [comment]
If somebody is looking for the same answer, the below code works for me:
I use this code to receive the SSO response SAML message from OKTA
```
$xml = base64_decode($_POST["SAMLResponse"]);
$deserializationContext = new \LightSaml\Model\Context\DeserializationContext();
$deserializationContext->getDocument()->loadXML($xml);
$response = new \LightSaml\Model\Protocol\Response(); 
$response->deserialize($deserializationContext->getDocument(), $deserializationContext);
$reader = $response->getFirstAssertion();
foreach ($reader->getFirstAttributeStatement()->getAllAttributes() as $attribute) {
	print sprintf("%s: %s\n", $attribute->getName(), $attribute->getFirstAttributeValue());
}
print $response->getID();
```

**Comment by CLG-Capacity** [comment]
I get a "Call to a member function getAllAttributes() on null" when calling $reader->getFirstAttributeStatement()->getAllAttributes()

**Comment by CLG-Capacity** [comment]
I've managed with:
```
$xml = base64_decode($_POST["SAMLResponse"]);
$key = \LightSaml\Credential\KeyHelper::createPublicKey(
	\LightSaml\Credential\X509Certificate::fromFile(APPPATH . 'okta.cert')
);
$deserializationContext = new \LightSaml\Model\Context\DeserializationContext();
$deserializationContext->getDocument()->loadXML($xml);
$response = new \LightSaml\Model\Protocol\Response();


$response->deserialize($deserializationContext->getDocument(), $deserializationContext);
$reader = $response->getFirstAssertion();

$IS_VALID = $reader->getSignature()->validate($key);
```

To validate the SAMLResponse from Okta URL using the cert from SSO app, but being a total newb to this I now have no idea where to grab any userName info with which to tie it to a user on the system.

**Comment by turkhero** [comment]
@CLG-Brainstorm 's comment should be included in the documentation. I spent a lot of time before finding this comment. Thanks, @CLG-Brainstorm .
