### ISSUE TITLE
Remove Request State

### ISSUE THREAD

**Issue by jejeman1110** [lightSAML/lightSAML#124]
Hello,
I'm tryig to config and use this bundle with a Symfony 3.4 application.
this doesn't work and I'm seeing something strange in the error log :
Removed request state "_78e8b87d943836fc0abb7fa3dcaaab5a0fa5c8070a"
Unknown InResponseTo '_78e8b87d943836fc0abb7fa3dcaaab5a0fa5c8070a'
CRITICAL17:01:57 | request | Uncaught PHP Exception LightSaml\Error\LightSamlContextException: "Unknown InResponseTo '_78e8b87d943836fc0abb7fa3dcaaab5a0fa5c8070a'" at ...
It remove the request state and after it says that it can't find the request state !!!! of course, it juste removes it just before !
This happens in the flush() method in the FlushRequestStatesAction class
I would like to understand why it did that ?
Thank you for your answer.

**Comment by helhum** [comment]
I'm having the same issue.
Request state [is removed](https://github.com/lightSAML/lightSAML/blob/377f04d1fb25f2fb2e72dabeff10b336f1cbe4c5/src/LightSaml/Action/Profile/FlushRequestStatesAction.php#L46)

Then it is [iterated over children](https://github.com/lightSAML/lightSAML/blob/377f04d1fb25f2fb2e72dabeff10b336f1cbe4c5/src/LightSaml/Action/Profile/FlushRequestStatesAction.php#L48) and request [state context of the children is flushed](https://github.com/lightSAML/lightSAML/blob/377f04d1fb25f2fb2e72dabeff10b336f1cbe4c5/src/LightSaml/Action/Profile/FlushRequestStatesAction.php#L49)

In my case this is the same state/id that was flushed before, thus does not exist any more.

Any hints? Thanks!
