### ISSUE TITLE
How to add SAMLRequest when redirecting to the IDP server?

### ISSUE THREAD

**Issue by glanes** [lightSAML/lightSAML#127]
Dear All,

I have installed a brand new project in symfony 4 and I am trying to authenticate in my IDP server. 
I already have an old project using simplesamlphp.

When the old project gets to the SSO server, simplesamlphp is sending a SAMLRequest and I believe the request has the information where the request come from.

**https://sso.clet.edu.au/adfs/ls/?SAMLRequest=pVJdaxsxEPwrh97vdB%2B2wcI2uDEhhqQ1sduHvARZ2qsFOumiXdXNv698l4IDxS99Ehrt7MyOdoGys71YRzq5Z3iLgJT97qxDMTwsWQxOeIkGhZMdoCAl9uunR1EXpeiDJ6%2B8ZVeU2wyJCIGMdyzbbpbsddaWdTWR9XRWzudtfWx1VevmqMtpXSk9aaCZlMdStVCx7AcETMwlS40SHTHC1iFJRwkqq3lelXk1PdS1mM5E07ywbJOmMU7SwDoR9Sg4R%2FSFskAF6FjIyKVukVvkLFv%2FNXfnHcYOwh7CL6Pg%2B%2FPjFZ2iBkefWqDpegtDYKeen89n3nkdLRSX6wXmOJ51LhWOaGrzrqyPOk%2BGcuxZtvtI84tx2rift4M8jkUoHg6HXb77tj%2Bw1eIiIYZgwuq%2F%2FXZAUkuS%2F7a74Ndii3GLviab283OW6Pes3sfOkm3p7ggRuftUCooSIcmmU1fYa0%2F3wWQBEtGIQLjq1Hy866u%2FgA%3D&RelayState=https%3A%2F%2Fstudent.clet.edu.au%2Fauth%2Fsaml%2Findex.php%3Fwantsurl%3Dhttps%253A%252F%252Fstudent.clet.edu.au%252F&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=iBGLuzw8CwPNOGHYTlrx7ktWgO6acSNfQWF5AVewzsfq%2FyC22kBMoM%2Fc6Fe76RikefsCEUzqJyocj1YeAyLKFxpgRTcPw%2BHtsaZnnNn%2BeYIgx%2F8vV%2BkAnakz%2FyFb68xG9kg06rVz1lV%2FfA9U5NozBDf%2BDsk5sk03euSnxyF0yVmCHTDVwyg9M7lrPJ5HroM50rpGEde44DWxFhGW6ZQyXuC1yn4l3ci%2F1VYfSxzMVPIXY35TvUuuSj8FMXAXO1L5BBo%2F1mY2Dy5P%2Fg4A9Wxg9TQuR8PHQi34%2FNYxrqEXQxAZnt5sju%2Fu7HCEBRXJlWefrBCSQkigLEigJJjiGelaoQ%3D%3D**

However on the lightSAML the redirect is being sent as 
**https://sso.clet.edu.au/adfs/ls**
 
Any help in what I am missing please?
Thank you so much

**Comment by tmilos** [comment]
Maybe it's sent with Http Post method so you don't see it in the url?

**Comment by glanes** [comment]
it is not being sent. When the authentication happens in the IDP server there is an error that he doesn't know where to go after.

**Comment by ankitce** [comment]
I was facing the same issue. The IDP sew some error happened after authentication and doesn't redirect.
The remedy you can try is placing the URL you provided to IDP in the Issuer. 
E.g. 
```
->setIssuer(new \LightSaml\Model\Assertion\Issuer(
        'THE_URL_PROVIDED_TO_IDP_IN_METADATA')
        )
```
