### ISSUE TITLE
SignatureWriter: SubjectName defaulted to false

### ISSUE THREAD

**Issue by eptflores** [lightSAML/lightSAML#13]
Part of the work I am doing requires that the x509 Subject be made available as part of the SAML response.  When I leverage the SignatureWriter class, I am able to see the Certificate data in the Saml but not the subject name.  

Looking at the library, I noticed that within the serialize method of the SignatureWriter class

$objXMLSecDSig->add509Cert($this->getCertificate()->getData(), false, false, array('subjectName' => **false**));

For my purposes, I changed 'subjectName' setting from false to true.

Please give the option to allow to set 'subjectName' either true or false;

**Comment by tmilos** [comment]
Released by [v1.0.2](https://github.com/lightSAML/lightSAML/releases/tag/1.0.2)
