### ISSUE TITLE
error install in laravel 7.6.2

### ISSUE THREAD

**Issue by dnitavm** [lightSAML/lightSAML#130]
I want to install lightSaml in Laravel 7.* but I cannot - I have a lot of errors.

"
...
- Conclusion: don't install lightsaml/lightsaml 1.4.1
...
- Can only install one of: symfony/event-dispatcher...
...
"

**Comment by leonrenkema** [comment]
We fixed it by using this fork: https://github.com/qikker-online/lightSAML

**Comment by spartancamera** [comment]
@leonrenkema can you share the composer.json parts where you require the package? For some reason when I run composer update, it is not pulling from the repository I specify. I am also confused that in the `composer.json ` file the `name` field was change to `qikker-online/lightsaml` whereas I expected it to stay `lightsaml/lightsaml`. I was hoping to receive some pointers to make this work.

**Comment by jspaetzel** [comment]
This will most likely work now with the 2.0.0 release.
