### ISSUE TITLE
PSR 7 Support

### ISSUE THREAD

**Issue by mnavarrocarter** [lightSAML/lightSAML#132]
Hi Milos!

I've noticed that this project has not been active for the past two years, so I was wondering if you will be willing to accept a BC PR implementing PSR-7 support, and also PSR-14. You can tag it as 2.0 if you are satisfied with the results.

I think the benefits of supporting PSR-7 in this library will be huge in terms of adoption and interoperability. 

I promise to implement it keeping the changes to a minimum and providing a migration guide to 2.0. What do you think?

**Comment by frostieDE** [comment]
I am not sure whether any PR would be accepted as this project seems abandoned. But I am willing to create a fork of this project (including the Symfony bundle and IDP library) as I depend on them for my projects.

**Comment by tmilos** [comment]
I'm sorry, I'm completely overwhelmed with other things. @mnavarrocarter @frostieDE would you like to be maintainers of this project?

**Comment by frostieDE** [comment]
@tmilos I am quite busy for myself but I think I am willing to give my best to bring this project further :-)

**Comment by frostieDE** [comment]
@mnavarrocarter We should not make this library PSR-14 compatible as it may not be comptable with Symfony 4.4 :-( See https://medium.com/@tdutrion/symfony-and-psr-14-event-dispatcher-f5a9db6740e7

**Comment by mnavarrocarter** [comment]
Hi @frostieDE I might be wrong but I think it is now. That was last year, but I'll double check. 

I'm quite busy too but if @frostieDE is up I am. We can share the work.

**Comment by frostieDE** [comment]
I am - I already pushed some changes in [my fork](https://github.com/lightSAML2)

**Comment by frostieDE** [comment]
@mnavarrocarter Problem is that Symfony 4.4 requires [`php >= 7.1.3`](https://github.com/symfony/symfony/blob/4.4/composer.json#L19) whereas PSR-14 requires PHP 7.2.

So there may be applications utilizing Symfony 4.4 and PHP 7.1.x - on the other hand, PHP 7.1 is not supported anymore. So we should formulate a rule of thumb of what platforms and versions of Symfony we want to support :-)
