### ISSUE TITLE
DOMDocument::createElementNS(): unterminated entity reference module=Users

### ISSUE THREAD

**Issue by rtuble** [lightSAML/lightSAML#138]
I'm trying to set up an SSO between Laravel and SuiteCRM, my problem is that the destination URL for Suite has parameters in it, and thus I'm getting the error below:

```
DOMDocument::createElementNS(): unterminated entity reference module=Users

  ##/vendor/lightsaml/lightsaml/src/LightSaml/Model/AbstractSamlModel.php

         */
        protected function manyElementsToXml($value, \DOMNode $node, SerializationContext $context, $nodeName = null, $namespaceUri = null)
        {
            if (false == $value) {
                return;
            }
     
            if (false == is_array($value)) {
                throw new \LogicException('value must be array or null');
            }
     
            foreach ($value as $object) {
                if ($object instanceof SamlElementInterface) {
                    if ($nodeName) {
                        throw new \LogicException('nodeName should not be specified when serializing array of SamlElementInterface');
                    }
                    $object->serialize($node, $context);
                } elseif ($nodeName) {
                    if ($namespaceUri) {
                        $child = $context->getDocument()->createElementNS($namespaceUri, $nodeName, (string) $object);
                    } else {
                        $child = $context->getDocument()->createElement($nodeName, (string) $object);
                    }
                    $node->appendChild($child);
                } else {
                    throw new \LogicException('Can handle only array of AbstractSamlModel or strings with nodeName parameter specified');
                }
            }
        }
```

I've been reading up their documentation as well and that is the correct URL: https://ipros24.ru/suitecrm-broken-saml-authentication/

Am I missing something here? Since I know the SAML works as I'm using it to connect to Mautic as well though that one has a URL that doesn't include any parameters.

**Comment by neamtua** [comment]
I'm running into the same issue here, also with suitecrm

**Comment by rtuble** [comment]
> 
> 
> I'm running into the same issue here, also with suitecrm

If you're running Lararvel 5.8 as well this solved it for me.

in here: `app/Auth/SamlAuth.php`

add this: "$clean_destination = str_replace("&amp;", "&", $destination);"

above: "$response = new \LightSaml\Model\Protocol\Response();"

and change "->setDestination($destination)" to "->setDestination($clean_destination)"

I know this is a bit hackish but that's the only way I made this work.

![image](https://user-images.githubusercontent.com/69242169/100061518-24df7480-2e69-11eb-8203-2b1e2255080a.png)
