### ISSUE TITLE
Loading LightSAML -Core : LightSaml/Context/AbstractContext.php

### ISSUE THREAD

**Issue by eptflores** [lightSAML/lightSAML#14]
I am attempting to load the LightSAML library on my web site and I am getting:

Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /api/libs/LightSaml/Context/AbstractContext.php on line 173

Error comes from debugPrintTree method with AbstractContext.php
        $result = array(
            $ownName => static::**class**, 
        );

PHP Version 5.4.45
Apache Version  2.2.31

Please disregard, it looks like I have to update  the php version on my website to at least 5.5 since class is a reserved keyword

**Comment by tmilos** [comment]
Yes, that [::class php 5.5 feature](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class) is used on lot of places and as mentioned in [composer.json](https://github.com/lightSAML/lightSAML/blob/master/composer.json) LightSAML requires at least PHP 5.5

PHP 5.4 has reached end of life on 2015-09-03 http://php.net/eol.php I don't think there's point in making LightSAML compatible with it.
