### ISSUE TITLE
Symfony 5 requirement

### ISSUE THREAD

**Issue by frostieDE** [lightSAML/lightSAML#140]
I suggest dropping the Symfony 5.x-only requirement and adding at least 4.4.x as an alternative. This makes the transition from Symfony 4.4 to 5.x easier.

As far as I can see there is (currently) no feature that requires Symfony 5.x.

WDYT?

**Comment by jspaetzel** [comment]
The `symfony/event-dispatcher` isn't backwards compatible with 4.x so we'd have to do something to support that dependency. I'd welcome a PR to get around this so long as it doesn't complicate things too much.

Otherwise for now lightSaml 2.x supports symfony 5 and 1.x supports symfony <= 4.
