### ISSUE TITLE
Symfony 5 configuration

### ISSUE THREAD

**Issue by szabi7** [lightSAML/lightSAML#148]
Hello,

I have this install on a symfony 5 project.
I want to setup IDP and SP (and another SP in django).
I don't know where to start... are there any files where the keys and parameters should go ?

**Comment by william-suppo** [comment]
Hello,

You can start by reading [this doc](https://www.lightsaml.com/LightSAML-Core/).

**Comment by FranzBruckner** [comment]
Hi,
thanks for your work on lightSAML!

Whats your suggestion for integration of lightSAML into Symfony5 / Symfony6 projects?
[SpBundle](https://github.com/lightSAML/SpBundle) looks a bit outdated?

**Comment by william-suppo** [comment]
Hi, I build my own bundle in my projects.

I'm not maintainer of SpBundle package, sry.
