### ISSUE TITLE
SAML Redirection page broken if browser extension adds an input

### ISSUE THREAD

**Issue by edvgui** [lightSAML/lightSAML#153]
Using the browser extension Yoroi breaks the redirection page, as it injects a hidden input field at the top of the page.  I am not aware of any other browser extension doing the same thing but there might be.

An input field is hidden in the page, and once the page is rendered, a javascript script simply selects the input and *click* on it.  https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Binding/SamlPostResponse.php#L63
The logic to select the input field just assumes that there will be only one input entry in the page, which is correct most of the time, but not in my specific case, and it bothers me.

An easy fix would be to select the input field based on an id.  I will propose a PR with this change shortly.

**Comment by william-suppo** [comment]
Thx for your PR.
