### ISSUE TITLE
Don't accept unsigned assertions if own SP entity descriptor says WantAssertionsSigned=true

### ISSUE THREAD

**Issue by bartvw** [lightSAML/lightSAML#27]
When using the SsoReceiveResponseProfileBuilder, an unsigned assertion is accepted even if our own SPSSODescriptor has WantAssertionsSigned="true".

**Comment by tmilos** [comment]
I think regardless of `WantAssertionsSigned` metadata attribute, all assertions must be signed. Saml Profiles 2.0 specs says

> The `Assertion` element(s) in the `Response` MUST be signed, if the HTTP POST binding is used

And LightSAML does not implement Artificat Resolution protocol, and receives Assertions only by HTTP POST.

`SsoReceiveResponseProfileBuilder` provides action built by `SsoSpReceiveResponseActionBuilder` and it itself does not check that Assertions are signed, but it adds composed assertion action built by the `ActionBuilderInterface $assertionActionBuilder` given in constructor, which by default is `SsoSpValidateAssertionActionBuilder` which at the end adds `AssertionSignatureValidatorAction` which returns w/out action if signature is missing https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Action/Assertion/Inbound/AssertionSignatureValidatorAction.php#L51

In the saml-metadata 2.0 specs it says 

> WantAssertionsSigned _Optional_
> Optional attribute that indicates a requirement for the `saml:Assertion` elements received by
> this service provider to be signed. If omitted, the value is assumed to be false. This requirement
> is in addition to any requirement for signing derived from the use of a particular profile/binding
> combination.

So, it seems in that case, unsigned assertions must be rejected, as by the HTTP POST binding being used.

I'll look into it, @bartvw thanks for the report.

The fix could be done in the `AssertionSignatureValidatorAction`, but that will just overload it with a new functionality/dependency, so maybe best solution might be to add an additional new action only for those purposes, that will be called before assertion signature verification.

**Comment by bartvw** [comment]
Also note that combined with the fact that the InResponseToValidatorAction also returns without action if the attribute is left out of the posted response, this could be a pretty big security risk, because it means anyone can fabricate a response based on any IdP's metadata. 
I was thinking of creating a separate issue for that, but unsolicited responses (IdP initiated) can actually be supported as long as the assertions are signed.

**Comment by tmilos** [comment]
`InResponseTo` is not required by saml specs and must be ommitted in case of IDP initiated SSO, so `InResponseToValidatorAction` is ok. Surely, as mentioned above, assertions must be signed to ensure authentication of the IDP that sent them.

**Comment by tmilos** [comment]
In #28 an exception is thrown on unsigned assertion, and it has been released as [1.0.6](https://github.com/lightSAML/lightSAML/releases/tag/1.0.6)

**Comment by bartvw** [comment]
That solves the issue. Thanks.

**Comment by putmanb** [comment]
Hello, I am one of the developers on the Shibboleth project.  A user of our SAML IdP brought to our attention this change to your library that is requiring Assertions issued under the Web SSO Profile to be signed.

I wanted to bring to your attention that the spec language you are quoting here is the original (non-errata) Profiles spec.  The language here was clarified in the errata and replaced as follows, from the last paragraph of section 4.1.3.5:

> For the purposes of the profile, either the &lt;Response> or the &lt;Assertion> element(s) in the 
&lt;Response> MUST be signed, if the HTTP POST binding is used, and MAY be signed if the HTTP-Artifact binding is used. If an &lt;EncryptedAssertion> element is present and a CBC-mode algorithm is used, then the &lt;Response>SHOULD be signed to ensure the ciphertext is integrity protected (see section 6.2 of [SAMLCore]).

You can see in the errata docs, either:

Redline diffs;
https://www.oasis-open.org/committees/download.php/56783/sstc-saml-profiles-errata-2.0-wd-07-diff.pdf

Merged document:
https://www.oasis-open.org/committees/download.php/56782/sstc-saml-profiles-errata-2.0-wd-07.pdf

So an unsigned Assertion conveyed via the POST binding is allowed as long as the enclosing Response is signed.

**Comment by tmilos** [comment]
Good point, will look after it. Thanks

**Comment by tigrang** [comment]
Is there any update on this?

**Comment by tmilos** [comment]
Not really, haven't got much time to work on this, but feel free to contribute, it should be fair easily... w/out much thinking it would require a new  Action/Assertion/Inbound that would fetch SP metadata from the context and throw exception if assertion isn't signed and metadata says it should be. And finally insert that new action to the `SsoSpValidateAssertionActionBuilder` in some place... for example before `AssertionSignatureValidatorAction`

**Comment by MatTheCat** [comment]
Just got hit by this issue while testing with https://stubidp.sustainsys.com/Metadata
I don't file like I can do anything about this; is there any progress?
