### ISSUE TITLE
[patch] wantAuthnRequestsSigned attribute is ignored 

### ISSUE THREAD

**Issue by noelg** [lightSAML/lightSAML#31]
Hi there,

I'm currently using a SAML identity provider which does not sign AuthnRequests in their development environment, and  `AssertionSignatureValidatorAction::requireSignature` is always set to true by `SsoSpValidateAssertionActionBuilder`. And we can't really change the behavior of `SsoSpValidateAssertionActionBuilder`, because it handles all the IdP, and some might require a signature when other don't.

This leads me to change `AssertionSignatureValidatorAction::doExecute` directly and retrieve wantAuthnRequestsSigned from the `PartyEntityDescriptor`, as seen here:

``` diff
diff --git a/src/LightSaml/Action/Assertion/Inbound/AssertionSignatureValidatorAction.php b/src/LightSaml/Action/Assertion/Inbound/AssertionSignatureValidatorAction.php
index 3418347..16aa331 100644
--- a/src/LightSaml/Action/Assertion/Inbound/AssertionSignatureValidatorAction.php
+++ b/src/LightSaml/Action/Assertion/Inbound/AssertionSignatureValidatorAction.php
@@ -51,8 +51,10 @@ class AssertionSignatureValidatorAction extends AbstractAssertionAction
     protected function doExecute(AssertionContext $context)
     {
         $signature = $context->getAssertion()->getSignature();
+        $wantSignature = $context->getProfileContext()->getPartyEntityDescriptor()->getFirstIdpSsoDescriptor()->getWantAuthnRequestsSigned();
+
         if (null === $signature) {
-            if ($this->requireSignature) {
+            if ($this->requireSignature && $wantSignature) {
                 $message = 'Assertions must be signed';
                 $this->logger->critical($message, LogHelper::getActionErrorContext($context, $this));
                 throw new LightSamlContextException($context, $message);
```

I also had to make a change in `IdpSsoDescriptor`, because wantAuthnRequestsSigned is transmitted as a string (false or true), which always cast to true when converted in boolean. So I used filter_var instead of (bool):

``` diff
diff --git a/src/LightSaml/Model/Metadata/IdpSsoDescriptor.php b/src/LightSaml/Model/Metadata/IdpSsoDescriptor.php
index 8a83077..376d5a4 100644
--- a/src/LightSaml/Model/Metadata/IdpSsoDescriptor.php
+++ b/src/LightSaml/Model/Metadata/IdpSsoDescriptor.php
@@ -34,7 +34,7 @@ class IdpSsoDescriptor extends SSODescriptor
      */
     public function setWantAuthnRequestsSigned($wantAuthnRequestsSigned)
     {
-        $this->wantAuthnRequestsSigned = $wantAuthnRequestsSigned !== null ? (bool) $wantAuthnRequestsSigned : null;
+        $this->wantAuthnRequestsSigned = $wantAuthnRequestsSigned !== null ? filter_var($wantAuthnRequestsSigned, FILTER_VALIDATE_BOOLEAN) : null;

         return $this;
     }
```

I'd be happy to share this as a pull request, but I have no idea if this is the proper way to fix it, or even if there's already a way to ignore signatures. Also, with this patch, we could probably get rid of `AssertionSignatureValidatorAction::requireSignature`.

thanks.

**Comment by bartvw** [comment]
> I'm currently using a SAML identity provider which does not sign AuthnRequests in their development environment

You probably mean the IdP doesn't sign the assertions. 

I think you're confused about what "WantsAuthnRequestsSigned" means. It means that the IdP expects the AuthnRequests generated by the SP to be signed. It has nothing to do with the signing of assertions by the IdP. 

Assertions are actually **required** to be signed if you're using the HTTP-POST binding. If the IdP you are using does not sign the assertions, it doesn't comply with the SAML standard and it's not safe to rely on it, because you can't be sure that the assertion actually came from the IdP.

**Comment by noelg** [comment]
Yeah, I'm probably a bit confused, I'm not really used to SAML yet.

What I can see is that `$context->getAssertion()->getSignature();` returns null, and that's why I guessed there's no signature. I just checked the POST response, and there's a "ds:Signature" element with a ds:SignatureValue. This must be the signature I'm looking for, I have to figure out why `->getSignature()` don't get it.

And I'm wondering then, if signatures are required, what the point of `requireSignature` then?

**Comment by bartvw** [comment]
> I just checked the POST response, and there's a "ds:Signature" element with a ds:SignatureValue. This must be the signature I'm looking for, I have to figure out why ->getSignature() don't get it.

It could be that the <Response> itself is signed but the <Assertion> isn't. You would have to look at the raw XML data to figure out what's going on there. 

> And I'm wondering then, if signatures are required, what the point of requireSignature then?

It could be useful for debugging. Also, if you're using the HTTP Artifact binding, signing is not required, because you can verify the source of the message in other ways.

**Comment by noelg** [comment]
You're right, <Response> is signed, but not <Assertion>.

**Comment by bartvw** [comment]
I think having the entire Response signed would be secure, because that includes the assertions inside it. Technically that's not what the spec says though: 

>  The <Assertion> element(s) in the <Response> MUST be signed, if the HTTP POST binding is used, and MAY be signed if the HTTPArtifact binding is used.

**Comment by noelg** [comment]
I think so, but indeed it's not what the spec says. I got in touch my idp about that, hopefully they will be able to fix it.

Thanks for your time, I think I can close this issue now!

**Comment by theNailz** [comment]
I'm having the same issue with two IdP's; see https://github.com/lightSAML/SpBundle/issues/83 as well.

@bartvw 
> It could be that **the .. itself is signed but the .. isn't**. You would have to look at the raw XML data to figure out what's going on there.

I think you're missing two words here, just like @noelg 

> You're right, .. is signed, but not ...

Could you explain what is the fix for this error/flow?

**Comment by theNailz** [comment]
FYI: I did get the flow working with https://capriza.github.io/samling/samling.html, but not with https://samltest.id/ or https://stubidp.sustainsys.com/
