### ISSUE TITLE
Signing and encryption documentation

### ISSUE THREAD

**Issue by isobit** [lightSAML/lightSAML#34]
Hey guys, just found this library, looks like a much better solution for SAML than SimpleSAMLPHP. I was wondering if there was anywhere I could find documentation on signing messages and encrypting assertions- there's mention of it in the cookbook, but it doesn't link anywhere. Thanks!

**Comment by tmilos** [comment]
Hello Josh,
LightSAML has documented SP functionality, and a Symfony SP Bundle. IDP was
started to be implemented with GPL license, but not quite polished to be as
user friendly as SP part.

Messages are signed with [SignatureWriter](https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Model/XmlDSig/SignatureWriter.php)

You can encrypt assertion with [EncryptedAssertionWriter](https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Model/Assertion/EncryptedAssertionWriter.php)

**Comment by isobit** [comment]
Thanks for pointing me to the right source- I have assertion encryption working but I am having trouble with signing. The `EncryptedAssertionWriter` has a method `encrypt` which receives the unencrypted assertion for serialization but I can't seem to find anything similar in `SignatureWriter`. This was my best guess for how it should be done:

```
        // serialize response to xml
        $respSerializationContext = new LightSaml\Model\Context\SerializationContext();
        $resp->serialize($respSerializationContext->getDocument(), $respSerializationContext);
        $signedRespWriter->serialize($respSerializationContext->getDocument(), $respSerializationContext);
        $respXml = $respSerializationContext->getDocument()->saveXML();
```

But that gives me `Fatal error:  Call to a member function importNode() on a non-object in /vagrant/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php on line 730`.

What would be the proper way of doing this?

**Comment by isobit** [comment]
I should also mention how `$signedRespWriter` is created:

```
        // sign the respones
        $cert = LightSaml\Credential\X509Certificate::fromFile($certFile);
        $signKey = new XMLSecurityKey(XMLSecurityKey::RSA_SHA1, array('type' => 'private'));
        $signKey->loadKey($keyFile, true, false);
        $signedRespWriter = new LightSaml\Model\XmlDSig\SignatureWriter($cert, $signKey);
```

**Comment by tmilos** [comment]
The `SignatureWriter` extends the `Signature`, and you have to set it to some SAML element that has signaure property before the serialization. You can not serialize them independently. You only serialize the root SAML elements - ie the Response, thus you should have only one `serialize` method call. For example:

``` php
$response = new Response();
$response->setSignaure(new SignatureWriter());
$context = new SerializationContext();
$response->serialize($context->getDocument(), $context);
print $context->getDocument()->saveXML();
```

Hope this helps

**Comment by isobit** [comment]
Ah, I missed `setSignature` in the source, that's exactly what I needed. Thanks!
