### ISSUE TITLE
Support for Symfony 3.0

### ISSUE THREAD

**Issue by cb8** [lightSAML/lightSAML#4]
At the moment this library as well as the Symfony bundles depend on Symfony 2 packages. Are there any plans to support Symfony 3.0? If so, will you release separate versions or do you intend to support both versions at the same time?

I would be glad to implement and test Symfony 3.0 integration in case you're interested.

**Comment by tmilos** [comment]
Sure, Symfony 3 must be supported. Havn't looked at v3 in details nor used it in some project, but just looked at [UPGRADE-3.0.md](https://github.com/symfony/symfony/blob/2.8/UPGRADE-3.0.md) and it seems only thing requiring changes to support Symfony 3 is the console part, and the only part of lighSAML using it is the [BuildSPMetadataCommand](/src/LightSaml/Command/BuildSPMetadataCommand.php) which kind of is not really necessary and the core of the stack. We can simplify and remove that one command from the lightSAML-Core and eventually create lightSAML-tools that command will be moved to, and by time more commands added to it. 

@cb8, what do you think? Is that command the only compatibility problem with Symfony 3?

BTW. You did a great job on those several PRs with CI, thanks

**Comment by tmilos** [comment]
Though, guess there will be much more to be done in [https://github.com/lightSAML/SpBundle](lightSAML/SpBundle) to support Symfony 3

**Comment by cb8** [comment]
Thank you for taking a look at it. I would start modifying lightSAML, the bridge and SpBundle for Symfony 3.0 if you're ok with that.

**Comment by cb8** [comment]
I think we can keep the commands in the core package as long as there is nothing like `LightSAML-SP` (as it exists for `LightSAML-IDP`).
