### ISSUE TITLE
Wrong installation directions for LightSAML Core

### ISSUE THREAD

**Issue by quizwedge** [lightSAML/lightSAML#41]
LightSAML Core Installation wants to Composer require version 2.0 or higher (https://www.lightsaml.com/LightSAML-Core/Installation/) but that fails as the latest version appears to be 1.0.8 (https://github.com/lightSAML/lightSAML/releases) Is there a later version that I'm missing?

**Comment by tmilos** [comment]
Will be handled by https://github.com/lightSAML/lightSAML.github.io/issues/7

**Comment by tmilos** [comment]
@quizwedge 
Installation instructions have been fixed https://www.lightsaml.com/LightSAML-Core/Installation/
Also, in SAML Response cookbook Status added https://www.lightsaml.com/LightSAML-Core/Cookbook/How-to-make-Response/

Thanks for the report
