### ISSUE TITLE
X509 in EncryptedAssertion

### ISSUE THREAD

**Issue by nuex** [lightSAML/lightSAML#44]
I can't seem to find a way to get the X509 cert to appear in an encrypted assertion using LightSAML. Here is a link to an encrypted assertion example: https://github.com/lightSAML/lightSAML/blob/master/resources/sample/Response/encryptedAssertion01.xml.

Is this possible?

**Comment by tmilos** [comment]
Yes, such output is made by lightsaml. Check https://www.lightsaml.com/LightSAML-Core/Cookbook/How-to-encrypt-Assertion/ if it helps

**Comment by nuex** [comment]
Thanks, @tmilos! I've actually been following the example there, but my encrypted assertion does not include the X509Certificate element.

I'm only encrypting the assertion, not signing it.

I'm curious about what options are necessary for LightSAML to produce that output.

**Comment by nuex** [comment]
Turns out X509Certificate is only used in a signed message and doesn't really make sense to have it in any other context. I think the example encrypted message has it because it's also an example of a signed, encrypted message.

Going to close this since this really isn't a bug and there isn't any missing functionality.

**Comment by tmilos** [comment]
@nuex you are right, encryption does not put in the certificate. That part is done by dependency lib robrichards/xmlseclibs. I have been able to implement it in lightsaml, just afterwards encryption is done by xmlseclibs, but I would rather see with @robrichards that to be implemented in xmlseclibs. 

That certificate does not play a critical role in encryption/decryption. You would anyway need a private key that matches that certificate to decrypt. It's just a convenience to indicate which private key should be used for decryption. Beside the certificate data itself , a certificate name could also be put according to xml sec schema. Those are supported by robrichards/xmlseclibs in signing, but seems to be omitted for encryption.
