### ISSUE TITLE
Class LightSaml\Resolver\Logout\LogoutSessionResolver does not exist

### ISSUE THREAD

**Issue by nateiler** [lightSAML/lightSAML#68]
The class \LightSaml\Bridge\Pimple\Container\Factory\ServiceContainerProvider attempts to register a LogoutSessionResolver class that does not exist.

**Comment by tmilos** [comment]
Yes, that's a tail from the not so best refactoring where logout functionality is moved to a separate lib https://github.com/lightSAML/lightSAML-logout

If you have lightsaml/lightsaml only then you should not call ``ServiceContainerInterface::getLogoutSessionResolver()``. If you have installed lightsaml/lightsaml-Logout also, then it should be working
