### ISSUE TITLE
Wrong nodeName for attribute in IdpSsoDescriptor

### ISSUE THREAD

**Issue by Ronnie-J** [lightSAML/lightSAML#69]
Hi.

Shouldn't the nodeName in IdpSsoDescriptor(https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Model/Metadata/IdpSsoDescriptor.php#L196) be `Attribute` and not `SingleSignOnService`?

I would expect to get the attributes when calling `getAllAttributes` but I get an empty array.

**Comment by tmilos** [comment]
@Ronnie-J You highlighted line 196 about Attibute and not SingleSignOnService. Not sure I understand your quesstion. 

Method call on line 183 is telling it to find all ``SingleSignOnService`` child xml nodes, deserialize them into ``LightSaml\Model\Metadata\SingleSignOnService`` objects and add them to IDPSSODescriptor object calling the ``addSingleSignOnService()`` method. 

Method call on line 193 is telling it to find all ``Attribute`` child xml nodes, deserialize them into ``LightSaml\Model\Assertion\Attribute`` objects and add them to IDPSSODescriptor object calling the ``addAttribute()`` method. 

Don't see anything wrong. I'm closing the issue. If you could you provide an example code demonstrating the malfunction, feel free to reopen it.
