### ISSUE TITLE
RelayState missing in the response

### ISSUE THREAD

**Issue by upwebdesign** [lightSAML/lightSAML#71]
I'm not sure if this is a bug or if I am doing something wrong, but after I build my response create the post binding and create the message context, the RelayState is missing from the original request and not passed through the form back to the SP, in this case Facebook for Work.

I ended up doing something like this:

```
$bindingFactory = new BindingFactory;`
$postBinding = $bindingFactory->create(SamlConstants::BINDING_SAML2_HTTP_POST);
$messageContext = new MessageContext();
$messageContext->setMessage($response)->asResponse();
** $message = $messageContext->getMessage();
** $message->setRelayState($request->RelayState);
$httpResponse = $postBinding->send($messageContext);

return $httpResponse->getContent();
```
The ** lines are added, but it would seem the RelayState should be included with the form automatically.

I'm not sure if this is the correct approach, but thought maybe someone would be willing to provide some feedback.

**Comment by tmilos** [comment]
I'm unable to reproduce issue you are describing. Take a look at PR #73 method ``test_relay_state_is_included_in_http_post()`` and modify it so you demonstrate a defect.

**Comment by upwebdesign** [comment]
@tmilos thanks for the reply. I will continue testing. I do have a working version of this, but I would prefer not have this work around.
