### ISSUE TITLE
Meta\SpMeta doesn't exist

### ISSUE THREAD

**Issue by EmilyShepherd** [lightSAML/lightSAML#74]
Docs refer to Meta\SpMeta but it doesn't appear to exist in the repo? Currently trying to port an SpMetaProviderInterface over from aerialship/lightsaml but it's not clear what those classes have become in the new structure.

**Comment by tmilos** [comment]
Could you point to the place where ``Meta\SpMeta`` is referred to in the docs?

**Comment by tmilos** [comment]
``SpMeta`` and related providers from aerialship/lightsaml are obsolete in new version of lightsaml/lightsaml. 

* NameIdFormat is not specified by default in AuthnRequest
* Binding to send AuthnRequest is determined from available bindings from IDP metadata with SAML2 HTTP POST binding as prefered
* ACS url is not specified in the AuthnRequest and is left to IDP to determine from own SP metadata
* SLO profile not directly implemented, thus ``getLogoutRequestBinding()`` is obsolete

So, you could just drop it.

Do you have some particular issue?

**Comment by EmilyShepherd** [comment]
`SpMeta` is mentioned [here](https://github.com/lightSAML/lightSAML/blame/877b07915202d6ce344836c930557aed4168eed0/doc/index.md#L60).

Ah fair, looks like I've been trying to port something that doesn't exist anymore haha, thanks! :)
