### ISSUE TITLE
Can't understand why warning is thrown.

### ISSUE THREAD

**Issue by chernecov** [lightSAML/lightSAML#75]
`$this->logger->warning(
    sprintf('Request state "%s" does not exist', $requestStateContext->getRequestState()->getId()),
    LogHelper::getActionContext($requestStateContext, $this)
);`

Is ->flush(...) executed two times. throwing a warning on second one. (because this id was removed by first call)

Can't understand why:
`if ($child instanceof AssertionContext) {
    $this->flush($child->getSubContext(ProfileContexts::REQUEST_STATE, null));
}`
is executed, and what is $child in this context.

Can anyone help?
Thanks in advance.

**Comment by tmilos** [comment]
@chernecov Mentioned warning is logged in ``FlushRequestStatesAction``. It's purpose is to remove seen IDs from the IdStore. It is used during the response receive to verify the ``InResponseTo`` values. It will call the ``flush`` method once for the Response and once for each Assertion. I would have to debug, but just by looking at the code, it seems that issue you reported can happen only if response has InResponseTo with the same value as the Assertion. 
Could you provide the Response XML you're getting this with?
