### ISSUE TITLE
Signing Assertion and verify signature + ArtifactResponse

### ISSUE THREAD

**Issue by varduefr** [lightSAML/lightSAML#76]
Hi, 
First of all, I really liked your easy implementation of the SAML protocol and the examples and the way you approached the library.
I'm trying to sign the Assertion instead of the Response and verify the signature but I'm getting an error. 
I also need to wrap the Response in an ArtifactResponse and sign the Assertion and then the ArtifactResponse. 
Do you think is ther an easy way of doing this in case is not implemented? I want to keep working with this fantastic library.
In case is not implemented do you know a similar libray/project that builds the ArtifactResponse as easy as the Response here and let you sign the Assertion and/or Response and/or ArtifactResponse?
Thanks!

**Comment by tmilos** [comment]
@varduefr  Thanks for the praise, glad to hear you like it. Unfortunately lightsaml doesn't have so far ``ArtifactResponse`` model implemented. If you could provide me with a valid XML I could implement the model relatively fast. But for it's signing, we would have to consult the specs, and I'm not sure I could afford the time now. 

And for the error you mentioned, it would really be helpful the error message text, stack trace, and ultimately the code (in a gist for example) producing that error. W/out any of these I can not help you.
