### ISSUE TITLE
CredentialResolverQuery::resolve() doesn't search anything

### ISSUE THREAD

**Issue by EmilyShepherd** [lightSAML/lightSAML#77]
`CredentialResolverQuery::resolve()` calls it's `CredentialResolverInterface`'s `resolve()` method but doesn't pass in a value for `$arrCredentials`. Am I missing something or will this always fail?

See: https://github.com/lightSAML/lightSAML/blob/master/src/LightSaml/Resolver/Credential/CredentialResolverQuery.php#L36

**Comment by tmilos** [comment]
The signature of the [credential resolver](https://github.com/lightSAML/lightSAML/blob/877b07915202d6ce344836c930557aed4168eed0/src/LightSaml/Resolver/Credential/CredentialResolverInterface.php) is such that it must get the criteria, but optionaly an array of credentials and returns an array of credentials. It's factored and implemented as a composite of several resolvers, where first in the chain is not using the credential array argument, but is returning credentials from the store. All other resolvers in the chain are working as filters to the provided credential array and thus using the argument. So, internally that argument is sometimes used, sometimes not, but the end user using the default factory should not provide that argument.
