### ISSUE TITLE
SymfonyBundle - configuration to enable signing

### ISSUE THREAD

**Issue by colinseaman** [lightSAML/lightSAML#79]
I see that LightSAML supports WantAuthnRequestsSigned signed requests, but I cant see anything in the documentation or examples which shows how to implement this in the configuration for the Symfony bundle.

Is this even possible right now?

**Comment by tmilos** [comment]
There's no out-of-the-box support for it. You could provide ``light_saml_symfony_bridge.own.entity_descriptor_provider.id`` configuration option and implement own ``EntityDescriptorProviderInterface``. For reference check [LightSAML Symfony bridge configuration](https://www.lightsaml.com/Symfony-Bridge/Configuration/).

**UPDATE**
Actually, I gave wrong answer above. If you as SP want to sign AuthnRequest you should implement your own TrustStore and set the ``signAuthnRequest`` to ``true`` in provided ``TrustOptions``
