### ISSUE TITLE
Logout doesn't work anymore after the first logout

### ISSUE THREAD

**Issue by wallish** [lightSAML/lightSAML#81]
Hi,

I have a weird situation in logout that i can't understand, so i come here to ask your help \:
- first login
- first logout (redirect to logout adfs page, success message and i get saml response) OK
- second login
- second logout (redirect to logout adfs page, success message, no saml response)
- comeback to the website and i am still connected and whenever i try to logout i have the same situation (logout not working)

Since the first logout work perfectly, i dont understand why the logout doesn't work anymore after the first logout, is it a adfs server setting ? or my logout code ?

```php
// inside /saml/logout
$authnRequest = new \LightSaml\Model\Protocol\LogoutRequest();
$authnRequest
    ->setDestination('https://fs.xxx.fr/adfs/ls/?wa=wsignout1.0')
    ->setIssuer(new \LightSaml\Model\Assertion\Issuer($this->_url . '/saml/logout'));

$certificate = \LightSaml\Credential\X509Certificate::fromFile(APPLICATION_PATH . '/config/cert/fs.xxx.fr.crt');
$privateKey = \LightSaml\Credential\KeyHelper::createPrivateKey(APPLICATION_PATH . '/config/cert/saml.key', '', true, XMLSecurityKey::RSA_SHA256);
$authnRequest->setSignature(new \LightSaml\Model\XmlDSig\SignatureWriter($certificate, $privateKey));

$bindingFactory = new \LightSaml\Binding\BindingFactory();
$redirectBinding = $bindingFactory->create(\LightSaml\SamlConstants::BINDING_SAML2_HTTP_REDIRECT);

$messageContext = new \LightSaml\Context\Profile\MessageContext();
$messageContext->setMessage($authnRequest);

$httpResponse = $redirectBinding->send($messageContext);
$this->_redirect($httpResponse->getTargetUrl());

```

**Comment by wallish** [comment]
I found the solution.

The problem was that i was using ws federation logout, instead of SAML logout.

Ws federation logout is using a specific url : 

` https://<sts.domain.com>/adfs/ls/?wa=wsignout1.0`

Saml logout are supposed to logout by sending the user to ADFS with a SAML Logout Request like : 
```php
$authnRequest = new \LightSaml\Model\Protocol\LogoutRequest();
$authnRequest->setNameID(new \LightSaml\Model\Assertion\NameID($_SESSION['samlNameId'], \LightSaml\SamlConstants::NAME_ID_FORMAT_TRANSIENT));
$authnRequest->setSessionIndex($_SESSION['samlSession']);
$authnRequest
    ->setDestination('https://fs.xxx.fr/adfs/ls/')
    ->setIssuer(new \LightSaml\Model\Assertion\Issuer($this->_url . '/saml'))
    ->setID(\LightSaml\Helper::generateID())
    ->setIssueInstant(new \DateTime())
 ;
$certificate = \LightSaml\Credential\X509Certificate::fromFile(APPLICATION_PATH . '/config/cert/fs.xxx.fr.crt');
$privateKey = \LightSaml\Credential\KeyHelper::createPrivateKey(APPLICATION_PATH . '/config/cert/saml.key', '', true, XMLSecurityKey::RSA_SHA256);
$authnRequest->setSignature(new \LightSaml\Model\XmlDSig\SignatureWriter($certificate, $privateKey));

$bindingFactory = new \LightSaml\Binding\BindingFactory();
$redirectBinding = $bindingFactory->create(\LightSaml\SamlConstants::BINDING_SAML2_HTTP_REDIRECT);

$messageContext = new \LightSaml\Context\Profile\MessageContext();
$messageContext->setMessage($authnRequest);

$httpResponse = $redirectBinding->send($messageContext);
```

**Comment by hsbsandrecv** [comment]
Hello Wallish,

I am facing this exact same situation, and I believe you are pointing to the right solution. However I am having trouble to determine where do I get this certificate  and  privatekey for the Logout Request.
I am using ADFS 3.0/4.0 from Microsoft and I do believe this certificate is the Token-Sign certificate of the IdP (Microsoft ADFS), I can export this cert, but it has no private key on export. 
By any chance do you have suggestion?

Regards,
