### ISSUE TITLE
Documentation references singing instead of signing

### ISSUE THREAD

**Issue by dgreeninger** [lightSAML/lightSAML#82]
https://www.lightsaml.com/LightSAML-Core/Cookbook/How-to-sign-SAML-message/
Not sure where to put this request in, but these sentences should probably be updated. Maybe do a search/replace on all the documentation, while you're there?

>  Since signing all SAML objects is the same, only the example of singing one of them is given below - signing of the AuthnRequest.

> In order to instantiate SignatureWrite and enable it for singing, you have to provide to it’s constructor (or set it later on, but before the serialization) your certificate and your private key.

>  Since signing all SAML objects is the same, only the example of **signing** one of them is given below - signing of the AuthnRequest.

> In order to instantiate SignatureWrite and enable it for **signing**, you have to provide to it’s constructor (or set it later on, but before the serialization) your certificate and your private key.

**Comment by tmilos** [comment]
Typo fixed in https://github.com/lightSAML/lightSAML.github.io/blob/master/LightSAML-Core/Cookbook/How-to-sign-SAML-message/index.md

Thanks
