### ISSUE TITLE
is LightSAML SP Bundle compatible with multiple firewalls context?

### ISSUE THREAD

**Issue by rgomez-syspay** [lightSAML/lightSAML#90]
hi! :)
This is more a question rather than a request, I have a successful set up of the LightSAML SP bundle on my symfony. It works well, but recently, we decided to add a normal form login to our site, apart of the SSO login.

To achieve this, I created a new firewall on Symfony 3.2, for the user login form. This firewall share the same pattern with the SSO firewall. The thing is, separately they both work fine (SSO and the new form) but together, once i log into one, it request to log into the other firewall. 

This happens because symfony doesnt share the context between firewalls. In order to sort out this, a new parameter is necessary on the firewall configuration called "context". I have tested creating a second login form and making it co-exists with the original login form. It works well, so when you login on one of the forms, the other is automatically understood as also validated. (to check, http://symfony.com/doc/3.2/reference/configuration/security.html#firewall-context)

So at the end its a pretty straightforward question, is the SP Bundle compatible with this "context" configuration option? :)

Thanks in advance!

**Comment by tmilos** [comment]
That's s feature of Symfony to indicate, so to say, which "session bag" to use in a firewall. LightSaml is ok regardless of the firewall context and you can use same context for several firewalls. Though, think it would be simpler you used both form and lightsaml listeners in the same firewall - then you won't needed the context option.

**Comment by rgomez-syspay** [comment]
indeed it worked perfectly with a single firewall :) thanks!
