### ISSUE TITLE
Would be great if this is better documented

### ISSUE THREAD

**Issue by martinberlin** [lightSAML/lightSAML#94]
I would like to collaborate documenting, but just need to make it work first :)

For example here:
https://github.com/lightSAML/lightSAML/blob/master/doc/index.md
is really not explained how to generate an Xml from the entityDescriptor. 

Section: Saving Metadata to Xml
$context = new Meta\SerializationContext();
$ed->getXml($context->getDocument(), $context);

The $ed has no method getXml. Can you please provide some working examples ? 

Thanks in advance!

**Comment by tmilos** [comment]
It's a leftover docs from v1... Will remove it... Try with https://www.lightsaml.com/LightSAML-Core/Cookbook/

**Comment by martinberlin** [comment]
Thanks @tmilos ! I managed to do it. Prepared a Lightsaml-signin IDP service for Symfony in my github public repositories using this package. 

Maybe it can help out others how to make a really simple IDP signin + metadata route.
