### ISSUE TITLE
Saml Message Examle

### ISSUE THREAD

**Issue by paymentplugins** [lightSAML/lightSAML#95]
Hi,

In **how_to_receive_saml_message.php** on line 12 it shows the response being instantiated from the binding->receive() method. However in reviewing the receive method of the HttpPostBinding class the receive method sets the message in the MessageContext class and does not provide a return value. 

It appears that to get the message one would call getMessage() on the MessageContext class or asResponse() if looking for a specific message class such as Response.

Kind Regards,

**Comment by miguelf11** [comment]
@paymentplugins you find any solution for this?

**Comment by kkolovos** [comment]
> @paymentplugins you found any solution for this?

After you use the  `$binding->receive($request, $messageContext);` just call the `$messageContext->asResponse()` to get the LightSaml\Model\Protocol\Response object
