### ISSUE TITLE
 <attribute> rather than <saml:attribute>

### ISSUE THREAD

**Issue by MajorTennis** [lightSAML/lightSAML#98]
appologies if this is not the right place to ask 

This is appearing in my ISSUER rather than in my response tag 
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
How might I get it into my response tag

<saml:attribute> rather than <attribute>
I have since adjusted the text in the assertion.php file and that  did it
"Assertion" -> "saml:Assertion" . haven't changed deserialize function.
This prefixed all children of assertion with <saml: . exactly what i needed

**Comment by tmilos** [comment]
LightSaml uses DomDocument which produces the XML string, and passes XSD validation by SAML schemas. So it does "work". It seems like other party you're sending messages to does understand all possible valid XMLs, and thus does not conform to the standard. Guess you would have to do your own solution that will conform to their standards.
